### ISSUE TITLE
Users are not been unfollowed after computer hibernate

### ISSUE THREAD

**Issue by rmcarv** [ann0nip/RemoveInstagramUnfollowers#2]
Hi! Thanks for the job and to share it! I tun first time and it was fine but my computer hibernate and I have to doit again, then, it'snot working anymore. It runs like everything is fine but the users are not been unfollowed.  I tried to restart the broewer  (chrome) and even use safari.

Any clue on what can I do to restart ?
![CleanShot 2023-06-25 at 05 14 48](https://github.com/ann0nip/RemoveInstagramUnfollowers/assets/18253649/a840c5f1-9bba-4e47-ad41-e158a04bad0a)

**Comment by ann0nip** [comment]
I just tested it, and the script is still working.
